name: Inform user about PR releases

on:
  pull_request:
    types: [opened]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post Comment on Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = `
            ## 🐳 PR release

            This PR does not have a release associated with it.

            To request a new release for this pull request, mention someone from the Nx team or the \`@nrwl/nx-pipelines-reviewers\`.   
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
